name: Android Pull Request & Master CI

on: push

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "app/build/outputs/apk/debug/app-debug.apk"
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo All files exists!
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk